return {
    "nvim-treesitter/nvim-treesitter",
    event = { "BufReadPost", "BufNewFile" },
    build = ":TSUpdate",
    dependencies = {
        "nvim-treesitter/nvim-treesitter-textobjects",
    },
    main = "nvim-treesitter.configs",
    opts = {
        ensure_installed = {
            "lua",
            "python",
            "vimdoc",
            "vim",
            "regex",
            "terraform",
            "sql",
            "dockerfile",
            "toml",
            "json",
            "gitignore",
            "yaml",
            "make",
            "cmake",
            "markdown",
            "markdown_inline",
            "bash",
        },
        auto_install = true,
        highlight = {
            enable = true,
            additional_vim_regex_highlighting = { "ruby" },
        },
        indent = { enable = true, disable = { "ruby" } },
    },
}
